config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/signup", to: "users#new"
  resources:users, except: [:index]
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources:microposts, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 140}
  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  before_save {self.email = email.downcase}
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :password, presence: true, length: { minimum:6 }, allow_nil: true
  has_secure_password
  
   # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  # ログイン済みのユーザーか確認
    def logged_in_user
      unless session[:user_id]
        flash[:warning] = "ログインしてください"
        redirect_to login_url
      end
    end
    
   
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  
  before_action :logged_in_user, only:[:create, :destroy]
  before_action :correct_user, only: :destroy
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      # 投稿成功
      flash[:success] = "投稿しました"
      redirect_to root_url
    else
      # 投稿失敗
      flash.now[:warning] = "投稿内容に誤りがあります"
      render "static_pages/home"
    end
  end
  
  def destroy
    @micropost.destroy
     flash[:success] = "削除しました"
     redirect_to root_url
  end
  
  private
    
    def micropost_params
      params.require(:micropost).permit(:content)
    end
    
     def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
     end
    
   
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ログイン処理
      log_in(user)
      flash[:success] = "ログインに成功しました"
      redirect_to user
    else
      # ログイン失敗時処理
      flash.now[:danger] = "メールアドレスまたはパスワードが違います"
      render "new"
    end
  end
  
  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @micropost = current_user.microposts.build if session[:user_id]
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user, only:[:edit, :update, :destroy]
  before_action :correct_user, only:[:edit, :update, :destroy]
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      # 登録成功時
      log_in(@user)
      flash[:success] = "ユーザー登録に成功しました"
      redirect_to @user
    else
      # 登録失敗時
      render "new"
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def destroy
    session.delete(:user_id)
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to root_url
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      # 更新成功
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to @user
    else
      # 更新失敗
      render "edit"
    end
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts
  end
  
  def destroy
    session.delete(:user_id)
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to root_url
  end

  
  private
    
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
    
     # 正しいユーザーか確認
    def correct_user
      @user = User.find(params[:id])
      unless @user == current_user
        redirect_to login_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # 渡されたユーザーでログイン
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # ログイン中のユーザーを返す
  def current_user
    if session[:user_id]
      return User.find_by(id: session[:user_id])
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
<%= @user.errors.count %> 個エラーがあります。
<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li>
    <%= msg %>
  </li>
  <% end %>
</ul>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    this is footer
</footer>

app/views/layouts/_header.html.erb
<header>
    <div class = headerItem>
    <h1><%= link_to "RAILS PRACTICE", root_path %></h1>
    <ul class = headLink>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <% if session[:user_id] %>
      <li><%= link_to "Profile", user_path(current_user) %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <li><%= link_to "Log out", logout_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render "/layouts/footer" %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>プログラミング学習中</p>

app/views/static_pages/home.html.erb
<% if session[:user_id] %>

<%= form_with(model: @micropost, local: true) do |f| %>
  <%= f.text_area :content, placeholder: "Compose new micropost..." %>
<%= f.submit "Post"%>
<% end %>

<% else %>
<h1>Welcome to Rails Practice!</h1>
<p>Rails 学習中です</p>
<h2><%= link_to "Sign up now!", signup_path %></h2>
<% end %>

app/views/users/edit.html.erb
<h1>Update your Profile<h1/>

 <%= form_with(model: @user, local: true) do |f| %>
   <%= render "layouts/error_messages" %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes" %>
    <% end %>
    
    <h1>Delete User</h1>
    <h2><%= link_to "Delete", user_path(@user), method: :delete, data: { confirm: "本当に削除しますか？" }  %></h2>  

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with(model: @user, local: true) do |f| %>
<%= render "layouts/error_messages" %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>

app/views/users/show.html.erb
<h1>Profile</h1>
<%= @user.name %>
<% if @microposts.any? %>
<%= @microposts.count %> Microposts
<ol>
  <% @microposts.each do |micropost| %>
  <li>
    <%= micropost.content %>
    <%= micropost.created_at %>
    <%= link_to "delete", micropost, method: :delete, 
    data:{ confirm: "削除しますか" } %>
  </li>
  <% end %> 
</ol>
<% end %>